$(document).ready(function(){
	$(".grid").hide();
        $("#list").addClass('active')
    $("#grid").click(function(){
        $(".grid").show();
        $(".list").hide();
        $(this).toggleClass('active');
        $("#list").removeClass('active');
    });
    $("#list").click(function(){
        $(".list").show();
        $(".grid").hide();
        $(this).toggleClass('active');
        $("#grid").removeClass('active');
    });
});